name: Update 02purl.details.txt

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:
  schedule:
    - cron: '0 */2 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  update-02purl-details:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
            perl-version: 5.36
            distribution: 'default'

      - name: Show Perl Version
        run: perl -v

      - name: Install Modules
        run: |
          cpanm -v
          cpanm --installdeps --with-develop --notest .

      - name: Generate 02purl.details.txt
        run: perl util/packages-to-purl

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add 02purl.details.txt
          git commit -s -m "Updated 02purl.details.txt" || echo "No changes to commit"
          git push
